apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app-jenkins 
  labels:
    app: helloworld-app
spec:
  selector:
    matchLabels:
        app: helloworld-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworld-app
    spec:
      containers:
        - name: helloworld-app
          image: 670166063118.dkr.ecr.us-east-1.amazonaws.com/eksdemo:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
